services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - wpsite

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    networks:
      - wpsite

  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      USERNAME: ${USERNAME}
    networks:
      - wpsite

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 256M
      VIRTUAL_HOST: admin.thangmay.epms.vn
      LETSENCRYPT_HOST: admin.thangmay.epms.vn
      LETSENCRYPT_EMAIL: your-email@example.com
    networks:
      - wpsite

  init-db:
    image: mysql:5.7
    depends_on:
      - db
    volumes:
      - ./db:/db
      - ./init.sql.sh:/docker-entrypoint-initdb.d/init.sql.sh
      - ./.env:/docker-entrypoint-initdb.d/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      URL_WORDPRESS: ${URL_WORDPRESS}
      WP_PORT: ${WP_PORT}
    entrypoint: ["/bin/sh", "/docker-entrypoint-initdb.d/init.sql.sh"]
    networks:
      - wpsite

  wordpress:
    depends_on:
      - db
      - init-db
    image: wordpress:latest
    restart: always
    volumes:
      - ./wp:/var/www/html
      - ./lib/themes:/var/www/html/wp-content/themes
      - ./lib/plugins:/var/www/html/wp-content/plugins
      - ./lib/languages:/var/www/html/wp-content/languages
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      VIRTUAL_HOST: thangmay.epms.vn
      LETSENCRYPT_HOST: thangmay.epms.vn
      LETSENCRYPT_EMAIL: your-email@example.com
    networks:
      - wpsite

networks:
  wpsite: