services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      USERNAME: ${USERNAME}
    networks:
      - wpsite

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 256M
      PMA_PORT: 3306
      VIRTUAL_HOST: ${URL_WORDPRESS}
      VIRTUAL_PATH: /admin
      TRUST_PROXY_HEADERS: 1
    networks:
      - wpsite

  init-db:
    image: mysql:5.7
    depends_on:
      - db
    volumes:
      - ./db:/db
      - ./init.sql.sh:/docker-entrypoint-initdb.d/init.sql.sh
      - ./.env:/docker-entrypoint-initdb.d/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      URL_WORDPRESS: ${URL_WORDPRESS}
      WP_PORT: ${WP_PORT}
    entrypoint: ["/bin/sh", "/docker-entrypoint-initdb.d/init.sql.sh"]
    networks:
      - wpsite

  wordpress:
    depends_on:
      - db
      - init-db
    image: wordpress:latest
    restart: always
    ports:
      - "${WP_PORT}:80"
    volumes:
      - ./wp:/var/www/html
      - ./lib/themes:/var/www/html/wp-content/themes
      - ./lib/plugins:/var/www/html/wp-content/plugins
      - ./lib/languages:/var/www/html/wp-content/languages
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    networks:
      - wpsite

networks:
  wpsite:
